root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main . && ./tmp/main -mock -out dist"
entrypoint = ["./tmp/main", "-server", "-port", "8080"]
include_ext = ["go", "html"]
exclude_dir = ["dist", "tmp", "testdata", ".github", ".git"]
delay = 200

[log]
time = false

[misc]
clean_on_exit = true
